#!/bin/sh -ex

# deps
DEPS="openssl ca-certificates"
DEPS_BUILD="wget"

# install deps
apk add --update $DEPS $DEPS_BUILD

# download murmur (mumble server)
MURMUR_VERSION=1.2.10
MURMUR_SHAONE="396326ed4a53fcb0db5f687c612801e5b436bfcd"

cd /tmp

wget \
	"https://github.com/mumble-voip/mumble/releases/download/${MURMUR_VERSION}/murmur-static_x86-${MURMUR_VERSION}.tar.bz2" \
	--output-document="murmur.tar.bz2"

echo "${MURMUR_SHAONE}  murmur.tar.bz2" | sha1sum -c -

tar --bzip2 -xf murmur.tar.bz2
cd murmur-static_x86-${MURMUR_VERSION}

mv murmur.x86 /usr/bin/murmurd

addgroup -S mumble-server
adduser -S -G mumble-server mumble-server

# clean up
apk del $DEPS_BUILD
rm -rf /var/cache/apk/*
rm -rf /tmp/*
