#!/bin/sh -ex

if [ ! -f /data/key.pem ]; then
	openssl req \
		-new \
		-newkey rsa:4096 \
		-nodes \
		-x509 \
		-days 3650 \
		-subj "/C=US/ST=mumble/L=mumble/O=mumble/CN=mumbleserver" \
		-keyout /data/key.pem \
		-out /data/cert.pem
fi

if [ ! -f /data/murmur-config.ini ]; then
	cp /opt/murmur-config.ini /data/murmur-config.ini
fi

chown -R mumble-server:mumble-server /data

exec murmurd -fg -ini /data/murmur-config.ini
