#!/bin/sh -ex

if [ ! -f /data/murmur/key.pem ]; then
	openssl req \
		-new \
		-newkey rsa:4096 \
		-nodes \
		-x509 \
		-days 3650 \
		-subj "/C=US/ST=murmur/L=murmur/O=murmur/CN=murmur" \
		-keyout /data/murmur/key.pem \
		-out /data/murmur/cert.pem

	chmod 400 /data/murmur/key.pem /data/murmur/cert.pem
fi

if [ ! -f /data/murmur/config.ini ]; then
	cp /opt/murmur-config.ini /data/murmur/config.ini
fi

chown -R murmur:murmur /data/murmur

exec murmurd -fg -ini /data/murmur/config.ini
